openproblems-bio/task_perturbation_prediction

- CHANGELOG.md
- src/task/control_methods/mean_across_celltypes/config.vsh.yaml
- src/task/control_methods/mean_across_celltypes/script.py
- src/task/control_methods/mean_across_compounds/config.vsh.yaml
- src/task/control_methods/mean_across_compounds/script.py
- src/task/control_methods/mean_outcome/config.vsh.yaml
- src/task/control_methods/mean_outcome/script.py
- src/task/workflows/run_benchmark/config.vsh.yaml
- src/task/workflows/run_benchmark/main.nf
> add mean baselines

- scripts/download_resources.sh
- src/common/sync_test_resources/config.vsh.yaml
- src/common/sync_test_resources/script.sh
> add sync resources component

- src/task/metrics/mean_cosine_sim/config.vsh.yaml
- src/task/metrics/mean_cosine_sim/script.py
- src/task/workflows/run_benchmark/config.vsh.yaml
- src/task/workflows/run_benchmark/main.nf
> add cosine similarity metric

- src/task/methods/jn_ap_op2/config.vsh.yaml
- src/task/methods/jn_ap_op2/script.py
jn_ap_op2 was added to methods
> JN_AP is added

- scripts/generate_kaggle_resources.sh
- scripts/run_benchmark.sh
- src/common/component_tests/run_and_check_output.py
- src/task/process_dataset/convert_kaggle_h5ad_to_parquet/config.vsh.yaml
- src/task/process_dataset/convert_kaggle_h5ad_to_parquet/script.py
- src/task/workflows/run_benchmark/config.vsh.yaml
- src/task/workflows/run_benchmark/main.nf
* Update the kaggle conversion scripts and datasets
* Add merged methods to benchmark wf
> Workflow_improvements

- main.nf
- nextflow.config
- scripts/run_benchmark_tw.sh
- src/common/nextflow_helpers/labels_tw.config
- src/task/methods/jn_ap_op2/config.vsh.yaml
- src/task/methods/scape/config.vsh.yaml
- src/task/methods/third_place/config.vsh.yaml
- src/task/workflows/run_benchmark/config.vsh.yaml
- src/task/workflows/run_benchmark/main.nf
* Add tower launch scripts
* Change component labels
* Add scape to workflow
> Update benchmark workflow

- src/task/process_dataset/workflow/config.vsh.yaml
> fix workflow dependencies

- .github/workflows/build.yml
> fix github action

- src/task/process_dataset/clean_pseudobulk/filter_genes.R
- src/task/process_dataset/run_limma/script.R
> update limma design matrix

- scripts/generate_resources.sh
- src/task/process_dataset/clean_pseudobulk/filter_genes.R
- src/task/process_dataset/run_limma/script.R
> use adjusted p-values

- src/task/methods/scape/script.py
> randomly select cell type if default does not exists

- src/common/nextflow_helpers/labels_tw.config
- src/task/methods/jn_ap_op2/config.vsh.yaml
- src/task/methods/lstm_gru_cnn_ensemble/config.vsh.yaml
- src/task/methods/nn_retraining_with_pseudolabels/config.vsh.yaml
- src/task/methods/pyboost/config.vsh.yaml
- src/task/methods/scape/config.vsh.yaml
- src/task/methods/transformer_ensemble/config.vsh.yaml
- src/task/methods/transformer_ensemble/script.py
- src/task/methods/transformer_ensemble/train.py
Fixes to methods based on the last benchmarking run:
* `lstm_gru_cnn_ensemble`: More shared mem
* `nn_retraining_with_pseudolabels`: Use nvcr tensorflow image to ensure tensorflow is already installed with the proper cuda libraries.
* `scape`: Use nvcr tensorflow image to ensure tensorflow is already installed with the proper cuda libraries.
* `transformer_ensemble`: Increase memory size, and fix device passing to several helper functions.
> Fix methods

- src/task/workflows/run_benchmark/main.nf
> add train_obs_zip to pyboost in wf

- src/task/workflows/run_benchmark/main.nf
> fix typo in wf

- _viash.yaml
- src/common/nextflow_helpers/labels_tw.config
- src/task/methods/lstm_gru_cnn_ensemble/config.vsh.yaml
> Bump method requirements

- src/task/methods/lstm_gru_cnn_ensemble/config.vsh.yaml
- src/task/metrics/mean_correlation/config.vsh.yaml
- src/task/metrics/mean_correlation/script.py
- src/task/metrics/mean_cosine_sim/config.vsh.yaml
- src/task/metrics/mean_rowwise_error/config.vsh.yaml
- src/task/workflows/run_benchmark/config.vsh.yaml
- src/task/workflows/run_benchmark/main.nf
* Increase memory limits of LSTM-GRU-CNN method
* Clean up metrics descriptions
* Add mean pearson / spearman component
> Multiple fixes

- src/task/metrics/mean_cosine_sim/config.vsh.yaml
- src/task/metrics/mean_cosine_sim/script.py
- src/task/metrics/mean_rowwise_error/config.vsh.yaml
- src/task/metrics/mean_rowwise_error/script.py
Update the threshold to 0.0001
> update threshold limits

- src/task/methods/lgc_ensemble_helpers/prepare_data.py
- src/task/methods/lgc_ensemble_prepare/script.py
> fix fillna

- src/task/process_dataset/generate_id_map/script.py
> fix id map generator

- scripts/run_benchmark_test.sh
- scripts/run_layerclip_tw.sh
- scripts/run_layert_tw.sh
- src/task/control_methods/mean_across_celltypes/config.vsh.yaml
- src/task/control_methods/mean_across_compounds/config.vsh.yaml
- src/task/control_methods/mean_outcome/config.vsh.yaml
- src/task/process_dataset/run_limma/config.vsh.yaml
- src/task/process_dataset/run_limma/script.R
> Add clipping to layer

- src/task/workflows/run_stability_analysis/main.nf
> store original id

- scripts/run_benchmark_test.sh
- scripts/run_benchmark_tw.sh
- scripts/run_stability_tw.sh
- scripts/sync_results.sh
- src/task/workflows/run_stability_analysis/config.vsh.yaml
> fix scripts

- src/process_dataset/add_uns_metadata/config.vsh.yaml
- src/process_dataset/bootstrap/config.vsh.yaml
- src/process_dataset/clean_pseudobulk/config.vsh.yaml
- src/process_dataset/compute_pseudobulk/config.vsh.yaml
- src/process_dataset/convert_h5ad_to_parquet/config.vsh.yaml
- src/process_dataset/convert_kaggle_h5ad_to_parquet/config.vsh.yaml
- src/process_dataset/filter_obs/config.vsh.yaml
- src/process_dataset/generate_id_map/config.vsh.yaml
- src/process_dataset/run_limma/config.vsh.yaml
> add back namespace
